---
# tasks file for nutanix-ansible-galaxy-role-init-api
  - ansible.builtin.include_tasks: check_variables.yml

  - ansible.builtin.include_tasks: set_auth_string.yml

  - ansible.builtin.include_tasks: set_api_urls.yml
    when:
      - nutanix_api_auth is defined

  - ansible.builtin.include_tasks: test_api.yml
    when:
      - nutanix_api_auth is defined
      - nutanix_api_v3 is defined

  - ansible.builtin.include_tasks: debug.yml
    when:
      - nutanix_debug
