---
  - name: Generate basic authorization string for PE
    set_fact:
      prism_auth_string: "{{ nutanix_username }}:{{ nutanix_password }}"
    no_log: True
    when:
      - nutanix_username is defined
      - nutanix_username != ""
      - nutanix_password is defined
      - nutanix_password != ""

  - name: Generate authorization header for PE
    set_fact:
      prism_api_auth: "Basic {{ prism_auth_string | b64encode(encoding='ascii') }}"
    no_log: True
    when: prism_auth_string is defined

  - name: Unset basic authorization string for PE
    set_fact:
      prism_auth_string: ""
    no_log: True
    when: prism_auth_string is defined
