---
  - name: v3 Test logon to PE
    uri:
      url: "{{ nutanix_api_v3 }}/users/me"
      method: GET
      validate_certs: "{{ validate_certs }}"
      body_format: json
      headers:
        Authorization: "{{ nutanix_api_auth }}"
      status_code: 200
      return_content: yes
    register: nutanix_api_login
    ignore_errors: no

  - name: Set Prism Type
    set_fact:
      nutanix_endpoint_prism_type: "{{ nutanix_api_login.x_ntnx_env }}"

  - name: Debug set_auth_string.yml variables
    debug:
      var: "{{ item }}"
    loop:
      - nutanix_api_login
      - nutanix_endpoint_prism_type
    when: nutanix_debug
